version: "3.7"
services:
    firstapi:
        command: npm run start:prod
        container_name: first-api-production
        build: .
        expose: 
            - 8080
        ports: 
            - 8080:8080
        volumes:
            - ./first-api:/app
            - /app/node_modules

    secondapi:
        command: npm run start:prod
        build: .
        container_name: second-api-production
        expose: 
            - 8081
        ports: 
            - 8081:8081
        volumes:
            - ./second-api:/app
            - /app/node_modules


