version: "3.7"
services:
    firstapi:
        image: try-multi-api:latest
        # build: .
        ports: 
            - "8080:8080"

    secondapi:
        image: try-multi-api:latest
        # build: .
        ports: 
            - "8081:8081"