version: "3.7"
services:
    firstapi:
        command: npm run dev
        container_name: first-api-development
        volumes:
            - ./first-api:/app
            - ./first-api/node_modules:/app/node_modules

    secondapi:
        command: npm run dev
        container_name: second-api-development
        volumes:
            - ./second-api:/app
            - ./first-api/node_modules:/app/node_modules


